<?php
    /*
     * @var \Revolut\Payment\Block\System\Config\WebhookSetup $block
    */
?>

<div id="addressValidationWebhookSetup">
    <p class="addressValidationWebhookSetupInfo" style="color:red;display:none">
        IMPORTANT: To enable Fast Checkout in Production mode, 
        ensure the address validation webhooks are set up correctly for the respective stores. 
    </p>
    <ul class="resultList" style="list-style: none;"></ul>
</div>

<script>
    var webhookSetupUrl = "<?=$escaper->escapeUrl($block->getAddressValidationWebhookSetupAjaxUrl())?>";

    require([
        "Revolut_Payment/js/address-validation-webhook-setup",
        "domReady!"
    ], function (AddressValidationWebhookSetup) {
        AddressValidationWebhookSetup().setup(webhookSetupUrl);
    })
</script>

