<?php
    /*
     * @var \Revolut\Payment\Block\System\Config\WebhookSetup $block
    */
?>

<div id="webhookSetup">
    <p class="webhookSetupInfo" style="color:red;display:none">
        IMPORTANT: To enable Payment Gateways in Production mode, 
        ensure webhooks are set up correctly for the respective stores.
    </p>
    <ul class="resultList" style="list-style: none;"></ul>
</div>

<script>
    var webhookSetupAjaxUrl = "<?=$escaper->escapeUrl($block->getWebhookSetupAjaxUrl())?>";

    require([
        "Revolut_Payment/js/webhook-setup",
        "domReady!"
    ], function (WebhookSetup) {
        WebhookSetup().setup(webhookSetupAjaxUrl);
    })
</script>

