<div class="revolut-fast-checkout-container">
    <style>
        #revolut-payment-request-fast-checkout-button iframe {
            height: 60px !important;
        }
    </style>
    <div id="revolut-pay-fast-checkout-button"></div>
    <div id="revolut-payment-request-fast-checkout-button"></div>
    <div id="revolut-fc-error-messages" class="mage-error"></div>

    <script>
        const productId = "<?= $escaper->escapeHtml($block->getProductId()) ?>";
        const productUrl = "<?= $escaper->escapeHtml($block->getProductUrl()) ?>";
        const cartUrl = "<?= $escaper->escapeHtml($block->getCartPageUrl()) ?>";
        const baseUrl = "<?= $escaper->escapeHtml($block->getStoreBaseUrl()) ?>";
        const revolutPayRedirectUrl = "<?= $escaper->escapeHtml($block->getRevolutPayRedirectUrl()) ?>";
        const isShoppingCart = "<?= $escaper->escapeHtml($block->getIsShoppingCart()) ?>";
        const storeCode = "<?= $escaper->escapeHtml($block->getStoreCode()) ?>";
        const locale = "<?= $escaper->escapeHtml($block->getLocaleCode()) ?>";
        const revolutSdk = "<?= $escaper->escapeHtml($block->getRevolutSdk()) ?>";
        const RevolutPaymentRequestPaymentMethodCode = "<?= $escaper->escapeHtml($block->getRevolutPaymentRequestPaymentMethodCode()) ?>";
        const RevolutPayPaymentMethodCode = "<?= $escaper->escapeHtml($block->getRevolutPayPaymentMethodCode()) ?>";
        const merchantPublicKey = "<?= $escaper->escapeHtml($block->getMerchantPublicKey()) ?>"

        if(!window.checkoutConfig.storeCode){
            window.checkoutConfig.storeCode = storeCode;
        }

        window.fastCheckoutConfig = {
            payment : {
                revolut : {
                    locale: locale,
                    productId: productId,
                    productUrl: productUrl,
                    cartUrl: cartUrl,
                    revolutSdk: revolutSdk,
                    merchantPublicKey: merchantPublicKey,
                    baseUrl: baseUrl,
                    revolutPayRedirectUrl: revolutPayRedirectUrl,
                    RevolutPaymentRequestPaymentMethodCode: RevolutPaymentRequestPaymentMethodCode,
                    RevolutPayPaymentMethodCode: RevolutPayPaymentMethodCode,
                }
            }
        };

        let locationPage = isShoppingCart ? "cart" : "product";

        require(
            [
            'domReady!',
            "mage/url",
            "mage/storage",
            'Revolut_Payment/js/view/payment/method-renderer/fast-checkout/revolut-payment-request-fast-checkout',
            'Revolut_Payment/js/view/payment/method-renderer/fast-checkout/revolut-pay-fast-checkout',
            ],
        function(domReady, urlBuilder, storage, RevolutPaymentRequest, RevolutPay)
        {
            storage.get(urlBuilder.build(`/rest/${storeCode}/V1/revolut/fast-checkout/params?location=${locationPage}`)).done(function (response) {
                window.fastCheckoutConfig.payment.revolut.revolutPaymentRequestThemeConfigs = JSON.parse(response.revolut_payment_request_theme_configs);
                window.fastCheckoutConfig.payment.revolut.revolutPayThemeConfigs = JSON.parse(response.revolut_pay_theme_configs);
                window.fastCheckoutConfig.payment.revolut.revolutSdk = response.revolut_sdk;
                RevolutPaymentRequest().initFastCheckoutButton(response.is_revolut_payment_request_active_location, isShoppingCart);
                RevolutPay().initFastCheckoutButton(response.is_revolut_pay_active_location, isShoppingCart);
            });
        });
    </script>
</div>
