<p style="color: #303030; font-size: 12px; margin: 5px 0; line-height: 1.5;">
    Earn cash rewards for every new customer you refer to Revolut — an easy way to earn back the cost of processing fees. Some of our merchants offset up to 50% of their fees through our Revolut Merchant Affiliate Programme. Plus, you get more customers who can pay in 1-click with Revolut Pay.
    <br>
    <a 
        style="color: #eb5202; text-decoration: underline;" 
        href="https://app.impact.com/campaign-campaign-info-v2/Revolut-Brand.brand?io=grsx9mz5Kjj7AcGYYbmrwolxR0LrkCUq%2FsZeCPGGvjDGfHSXZaNeJa7eXPb9iTc0" 
        target="_blank">
        Apply to Affiliate Programme
    </a> 
    or 
    <a
        style="color: #eb5202; text-decoration: underline;" 
        href="https://developer.revolut.com/docs/resources/marketing-assets-guidelines/marketing-guidelines#affiliate-program---get-paid-for-introducing-new-customers-to-revolut" 
        target="_blank">
        find out more
    </a>
</p>