<div id="revolut-reward-banner-widget"></div>

<script>
    window.revolutBannerConfig  = <?= $escaper->escapeHtml($block->getOrderDetails()) ?>;    
    if(window.revolutBannerConfig && window.revolutBannerConfig.isRewardBannerActive){
        require([
            'Revolut_Payment/js/view/reward/upsell-banner'
            ], 
        function(RevolutRewardBanner)
        {
            RevolutRewardBanner.init();
        });
    }
</script>